# Generated by Django 3.1.4 on 2021-01-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='date_lastvote',
        ),
    ]
