# Generated by Django 3.1.4 on 2020-12-22 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_lastvote',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 45, 10, 687242)),
        ),
    ]
