# Generated by Django 3.1.4 on 2020-12-22 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20201222_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 47, 52, 609243)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_lastvote',
            field=models.DateTimeField(blank=True),
        ),
    ]
