# Generated by Django 3.1.4 on 2020-12-22 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20201222_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 48, 51, 868243)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_lastvote',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 48, 51, 868243)),
        ),
    ]
