# Generated by Django 3.1.4 on 2020-12-22 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20201222_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_lastvote',
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 50, 42, 37243)),
        ),
    ]
