# Generated by Django 3.1.4 on 2020-12-22 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20201222_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_lastvote',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 51, 45, 480275)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 51, 45, 480275)),
        ),
    ]
