# Generated by Django 3.1.4 on 2020-12-22 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20201222_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_lastvote2',
        ),
        migrations.AddField(
            model_name='poll',
            name='date_lastvote',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 56, 5, 753243)),
        ),
    ]
