# Generated by Django 3.1.4 on 2020-12-22 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_auto_20201222_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_lastvote',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 57, 56, 677189)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 57, 56, 677189)),
        ),
    ]
